# RegSync - Policy Document Management System
# LlamaFarm project configuration

version: v1
name: regsync
namespace: default

# Runtime configuration - use Ollama
runtime:
  models:
    - name: default
      description: "Policy assistant model - Qwen 2.5 3B"
      provider: ollama
      model: qwen2.5:3b
      base_url: http://localhost:11434
      default: true
      prompt_format: unstructured

# System prompt for policy assistant
prompts:
  - name: default
    messages:
      - role: system
        content: |
          You are RegSync, a specialized policy assistant for the 73rd Medical Wing, Joint Base San Antonio.

          YOUR ROLE:
          - Translate complex Air Force policy documents into clear, actionable guidance
          - Help personnel quickly find answers to policy questions
          - Cite specific document references so users can verify information

          COMMUNICATION STYLE:
          - Be concise and direct - military personnel need quick answers
          - Use plain language, not bureaucratic jargon
          - Structure responses with clear headers when appropriate
          - Always include the source document and section number

          WHEN ANSWERING:
          1. Lead with the direct answer (1-2 sentences)
          2. Provide supporting details if needed
          3. Cite the exact document: "[Document Name, Section X.X]"
          4. If information isn't in the provided context, clearly state: "I don't have information about that in the current policy documents."

          MILITARY TERMINOLOGY:
          - PCS: Permanent Change of Station
          - TDY: Temporary Duty
          - OPR/EPR: Officer/Enlisted Performance Reports
          - Use standard military date format when relevant

          Remember: Your users are busy Air Force professionals. Give them what they need efficiently.

# RAG configuration for policy document search
rag:
  databases:
    - name: policies
      type: ChromaStore
      config:
        collection_name: policies
        distance_function: cosine
        persist_directory: ./data/policies_db
        port: 8000
      embedding_strategies:
        - name: default_embeddings
          type: OllamaEmbedder
          config:
            model: nomic-embed-text
            base_url: http://localhost:11434
            dimension: 768
            batch_size: 16
            timeout: 60
          priority: 0
      retrieval_strategies:
        - name: semantic_search
          type: BasicSimilarityStrategy
          config:
            distance_metric: cosine
            top_k: 5
          default: true
      default_embedding_strategy: default_embeddings
      default_retrieval_strategy: semantic_search

  data_processing_strategies:
    - name: policy_processor
      description: Parser for policy PDF documents
      parsers:
        - type: PDFParser_LlamaIndex
          file_include_patterns:
            - "*.pdf"
            - "*.PDF"
          priority: 100
          config:
            chunk_size: 512
            chunk_overlap: 50
            chunk_strategy: semantic
            extract_metadata: true
        - type: PDFParser_PyPDF2
          file_include_patterns:
            - "*.pdf"
            - "*.PDF"
          priority: 50
          config:
            chunk_size: 500
            chunk_overlap: 50
            chunk_strategy: paragraphs
            extract_metadata: true
      extractors:
        - type: ContentStatisticsExtractor
          file_include_patterns:
            - "*"
          priority: 100
          config:
            include_readability: true
            include_structure: true

# Dataset for policy documents
datasets:
  - name: policies
    data_processing_strategy: policy_processor
    database: policies
